"""add category_en to items

Revision ID: 228fb74b118e
Revises: 3e7bacf9e868
Create Date: 2026-03-27 06:51:24.824357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228fb74b118e'
down_revision: Union[str, None] = '3e7bacf9e868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_en', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category_en')
    # ### end Alembic commands ###
