"""add last_upload_at to listings

Revision ID: 409711574e1b
Revises: 6b7ff7316745
Create Date: 2026-03-24 07:10:17.316920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409711574e1b'
down_revision: Union[str, None] = '6b7ff7316745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('last_upload_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'last_upload_at')
    # ### end Alembic commands ###
