"""initial tables

Revision ID: 6b7ff7316745
Revises: 
Create Date: 2026-03-24 05:56:57.140478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7ff7316745'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name_ja', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('data_center', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('listings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('hq', sa.Boolean(), nullable=False),
    sa.Column('retainer_name', sa.String(length=100), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_fetched_at', 'listings', ['fetched_at'], unique=False)
    op.create_index('ix_listings_item_world', 'listings', ['item_id', 'world_id'], unique=False)
    op.create_table('price_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Integer(), nullable=False),
    sa.Column('max_price', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('hq', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_summary_unique', 'price_summary', ['item_id', 'world_id', 'date', 'hq'], unique=True)
    op.create_table('sale_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('hq', sa.Boolean(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_history_item_world', 'sale_history', ['item_id', 'world_id'], unique=False)
    op.create_index('ix_sale_history_sold_at', 'sale_history', ['sold_at'], unique=False)
    op.create_index('ix_sale_history_unique', 'sale_history', ['item_id', 'world_id', 'sold_at', 'price_per_unit', 'quantity'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_history_unique', table_name='sale_history')
    op.drop_index('ix_sale_history_sold_at', table_name='sale_history')
    op.drop_index('ix_sale_history_item_world', table_name='sale_history')
    op.drop_table('sale_history')
    op.drop_index('ix_price_summary_unique', table_name='price_summary')
    op.drop_table('price_summary')
    op.drop_index('ix_listings_item_world', table_name='listings')
    op.drop_index('ix_listings_fetched_at', table_name='listings')
    op.drop_table('listings')
    op.drop_table('worlds')
    op.drop_table('items')
    # ### end Alembic commands ###
