"""add lodestone_id to items

Revision ID: e02ae8e45610
Revises: 409711574e1b
Create Date: 2026-03-24 16:06:25.172451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02ae8e45610'
down_revision: Union[str, None] = '409711574e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('lodestone_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'lodestone_id')
    # ### end Alembic commands ###
